version: '3.8'

services:
  webapp:

    image: php:apache

    environment:
      - USERNAME=toto
      - PASSWORD=python

    volumes:
      - ./website:/var/www/html
    depends_on:
      - api

    ports:
      - "8000:80"

    networks:
      - student
    
    restart: always

  api:

    build: ./simple_api
    container_name: student-api

    ports :
      - 50000:5000
    volumes :
      - ./simple_api/student_age.json:/data/student_age.json

    networks:
      - student
networks:
  student :




